name: Test Model

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: "Caminho do CSV de teste"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test
        run: python scripts/test.py ${{ github.event.inputs.test_file }}

      - name: Zip results
        run: |
          cd results
          zip -r ../results.zip .

      - name: Upload predictions
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.zip
