name: Test Model

on:
  workflow_dispatch:
    inputs:
      csv_file:
        description: "Caminho do CSV de teste dentro da pasta data/"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Baixar modelo treinado
        uses: actions/download-artifact@v4
        with:
          name: modelo_treinado
          path: models/

      - name: Executar script de teste
        run: python scripts/test.py data/${{ github.event.inputs.csv_file }}

      - name: Enviar resultado do teste como artefato
        uses: actions/upload-artifact@v4
        with:
          name: resultado_teste
          path: results/

